"""workout and exercise tables

Revision ID: 8aa24ebd355c
Revises: 293c4c2cdbb2
Create Date: 2020-03-29 18:03:59.553901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aa24ebd355c'
down_revision = '293c4c2cdbb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('muscle_group', sa.String(length=64), nullable=True),
    sa.Column('muscle', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_muscle'), 'exercise', ['muscle'], unique=False)
    op.create_index(op.f('ix_exercise_muscle_group'), 'exercise', ['muscle_group'], unique=False)
    op.create_index(op.f('ix_exercise_name'), 'exercise', ['name'], unique=True)
    op.create_table('workout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_type', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_timestamp'), 'workout', ['timestamp'], unique=False)
    op.create_index(op.f('ix_workout_workout_type'), 'workout', ['workout_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_workout_type'), table_name='workout')
    op.drop_index(op.f('ix_workout_timestamp'), table_name='workout')
    op.drop_table('workout')
    op.drop_index(op.f('ix_exercise_name'), table_name='exercise')
    op.drop_index(op.f('ix_exercise_muscle_group'), table_name='exercise')
    op.drop_index(op.f('ix_exercise_muscle'), table_name='exercise')
    op.drop_table('exercise')
    # ### end Alembic commands ###
